return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "blade-formatter",
      "dotenv-linter",
      "duster",
      "emmet-language-server",
      "emmet-ls",
      "eslint-lsp",
      "intelephense",
      "lua-language-server",
      "php-cs-fixer",
      "phpcs",
      "prettier",
      "prisma-language-server",
      "quick-lint-js",
      "rustywind",
      "shfmt",
      -- "stimulus-language-server",
      "stylua",
      "tailwindcss-language-server",
      "trivy",
      "typescript-language-server",
      "js-debug-adapter",
      "sqlfluff",
      "prettier-php",
    },
  },
}
